apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: {{ template "vote-app.name" . }}-demo
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: {{ template "vote-app.name" . }}-postgress-pod
    app: {{ template "vote-app.name" . }}-demo
