apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vote-app.name" . }}-redis-deploy
  labels:
    name: {{ template "vote-app.name" . }}-redis-deploy
    app: {{ template "vote-app.name" . }}-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      name: {{ template "vote-app.name" . }}-redis-pod
      app: {{ template "vote-app.name" . }}-demo
  template:
    metadata:
      name: {{ template "vote-app.name" . }}-redis-pod
      labels:
          name: {{ template "vote-app.name" . }}-redis-pod
          app: {{ template "vote-app.name" . }}-demo
    spec:
        containers:
          - name: redis
            image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
            ports:
              - containerPort: 6379
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - redis-pod
              topologyKey: "kubernetes.io/hostname"

