apiVersion: v1
kind: Service
metadata:
  name: {{ include "Votinghelm.fullname" . }}-redis-service
  labels:
    name: {{ include "Votinghelm.fullname" . }}-redis-service
    app: {{ .Values.applicationName }}
    {{- include "Votinghelm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    name: {{ include "Votinghelm.fullname" . }}-redis-pod
    app: {{ .Values.applicationName }}
    {{- include "Votinghelm.selectorLabels" . | nindent 4 }}
