apiVersion: v1
kind: Service
metadata:
  name: {{ include "Votinghelm.fullname" . }}-result-service
  labels:
    name: {{ include "Votinghelm.fullname" . }}-result-service
    app: {{ .Values.applicationName }}
    {{- include "Votinghelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.result.service.type }}
  ports:
    - port: {{ .Values.result.service.port }}
      targetPort: {{ .Values.result.service.targetPort }}
      nodePort: {{ .Values.result.service.NodePort }}
  selector:
    name: {{ include "Votinghelm.fullname" . }}-result-pod
    app: {{ .Values.applicationName }}
    {{- include "Votinghelm.selectorLabels" . | nindent 4 }}
